# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{threadz}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Aller"]
  s.date = %q{2009-12-19}
  s.email = %q{nanodeath@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/threadz.rb",
     "lib/threadz/atomic_integer.rb",
     "lib/threadz/batch.rb",
     "lib/threadz/directive.rb",
     "lib/threadz/sleeper.rb",
     "lib/threadz/thread_pool.rb",
     "spec/atomic_integer_spec.rb",
     "spec/spec_helper.rb",
     "spec/threadz_spec.rb",
     "threadz.gemspec"
  ]
  s.homepage = %q{http://github.com/nanodeath/threadz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby threadpool library to handle threadpools and make batch jobs easier.}
  s.test_files = [
    "spec/atomic_integer_spec.rb",
     "spec/threadz_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

